#!/usr/bin/python

# This is a simple echo bot using the decorator mechanism.
# It echoes any incoming text messages.

import telebot

API_TOKEN = '1497044855:AAFpPeeoo4Idt_cFhbDVLRfHXngIPDiXTkM'

bot = telebot.TeleBot(API_TOKEN)


# Handle '/start' and '/help'
@bot.message_handler(commands=['help', 'start'])
def send_welcome(message):
    bot.reply_to(message, """\
Ghesboro so imbriagon_bot!
Te voito na gota de vin? No perchè se te voi gho anca el gin, dime ti insomma...\
""")


# Handle all other messages with content_type 'text' (content_types defaults to ['text'])
@bot.message_handler(func=lambda message: True)
def echo_message(message):
    if message.text=='Ciao':
      bot.reply_to(message, 'Non sta rompar i cojoni')
    elif message.text=='Buonanotte':
      bot.reply_to(message, 'Spero par sempre diocan')


bot.polling()
